Bmark_solvers with solver_specific stats bug
JuliaSmoothOptimizers/SolverBenchmark.jl pull request #171
Opened 2024-11-11 22:27 UTC by MaxenceGollier

Discussed in #170

2024-11-11 22:37 UTC, MaxenceGollier commented on src/run_solver.jl
> +    end # We don't print the first problems that have exceptions/skips when colstats is not default...
I don't know if my approach is optimal, what might happen here is that colstats does not have its default value, then if the n first iterations are skipped/throw an error, then the first n iterations will not be printed.

2024-11-11 22:38 UTC, tmigot commented
Thanks @MaxenceGollier for the PR. I am just wondering if counting the number of unsuccessful before the first solve add updating this line:
https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/360eb42a04beca2a57ee6e894481ebe60695a6b0/src/run_solver.jl#L129
with `k => Vector{Union{typeof(v), Missing}}(undef, nb_unsuccessful),` woudl have been a simpler solution?

2024-11-12 16:26 UTC, MaxenceGollier commented
> Thanks @MaxenceGollier for the PR. I am just wondering if counting the number of unsuccessful before the first solve add updating this line:
> 
> https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/360eb42a04beca2a57ee6e894481ebe60695a6b0/src/run_solver.jl#L129
> 
> 
> with `k => Vector{Union{typeof(v), Missing}}(undef, nb_unsuccessful),` woudl have been a simpler solution?

Definitely, thank you.

2024-11-12 22:12 UTC, tmigot approved these changes
LGTM, thanks @MaxenceGollier

2024-11-12 22:21 UTC, MaxenceGollier commented
@dpo can you take a look and merge if you think this is good ?

2024-11-18 15:34 UTC, dpo commented
What is this error? https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/actions/runs/11801745210/job/32891059863?pr=171#step:9:15

2024-11-18 15:43 UTC, dpo requested changes

2024-11-18 15:43 UTC, dpo commented on test/test_bmark.jl
> +      end
```suggestion
      skipif = problem -> problem.meta.ncon == 0,
```

2024-11-18 15:43 UTC, dpo commented on test/test_bmark.jl
> +          end
```suggestion
          callback = (nlp, solver, stats) -> set_solver_specific!(stats, :foo, 1),
```

2024-11-18 15:44 UTC, tmigot commented
> What is this error? https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/actions/runs/11801745210/job/32891059863?pr=171#step:9:15

https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/issues/172

2024-11-21 18:41 UTC, farhadrclass commented
@MaxenceGollier  does this fix our #167 issue as well?

2024-11-21 18:55 UTC, dpo approved these changes

2024-11-21 18:55 UTC, merged